"use client"

import type React from "react"

import { useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ArrowLeft, Wrench } from "lucide-react"

const CATEGORIES = [
  "Plumbing services",
  "Electrical services",
  "Cleaning Services",
  "Moving services",
  "Tutoring services",
]

export default function ProfessionalLoginPage() {
  const router = useRouter()
  const [userName, setUserName] = useState("")
  const [businessName, setBusinessName] = useState("")
  const [category, setCategory] = useState("")
  const [isNewUser, setIsNewUser] = useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (userName.trim() && (!isNewUser || (businessName.trim() && category))) {
      // Store professional data in sessionStorage for demo purposes
      sessionStorage.setItem("professionalName", userName)
      if (isNewUser) {
        sessionStorage.setItem("businessName", businessName)
        sessionStorage.setItem("category", category)
      }
      
      // Initialize mock data if not already present
      if (!sessionStorage.getItem("professionalJobs")) {
        const INITIAL_JOBS = [
          {
            id: "J1",
            jobName: "Kitchen Sink Repair",
            customerName: "john_s",
            date: "2025-09-15",
            paymentReceived: 250,
            materialsCost: 50,
            paymentMethod: "card",
            paymentStatus: "paid",
            notes: "Fixed leaking pipes and replaced worn gaskets",
          },
          {
            id: "J2",
            jobName: "Bathroom Plumbing Installation",
            customerName: "sarah_m",
            date: "2025-09-20",
            paymentReceived: 800,
            materialsCost: 200,
            paymentMethod: "cash",
            paymentStatus: "paid",
          },
          {
            id: "J3",
            jobName: "Water Heater Maintenance",
            customerName: "mike_t",
            date: "2025-09-25",
            paymentReceived: 350,
            materialsCost: 75,
            paymentMethod: "card",
            paymentStatus: "paid",
          },
          {
            id: "J4",
            jobName: "Emergency Pipe Repair",
            customerName: "emily_r",
            date: "2025-10-01",
            paymentReceived: 450,
            materialsCost: 100,
            paymentMethod: "manual",
            paymentStatus: "pending",
          },
        ]
        sessionStorage.setItem("professionalJobs", JSON.stringify(INITIAL_JOBS))
      }
      
      if (!sessionStorage.getItem("professionalExpenses")) {
        const INITIAL_EXPENSES = [
          {
            id: "E1",
            professionalId: userName,
            name: "Materials for Kitchen Sink Repair",
            category: "materials",
            amount: 50,
            date: "2025-09-15",
            relatedJobId: "J1",
            relatedJobName: "Kitchen Sink Repair",
            notes: "Auto-generated from job: Kitchen Sink Repair",
            autoGenerated: true,
          },
          {
            id: "E2",
            professionalId: userName,
            name: "Materials for Bathroom Plumbing Installation",
            category: "materials",
            amount: 200,
            date: "2025-09-20",
            relatedJobId: "J2",
            relatedJobName: "Bathroom Plumbing Installation",
            notes: "Auto-generated from job: Bathroom Plumbing Installation",
            autoGenerated: true,
          },
          {
            id: "E3",
            professionalId: userName,
            name: "Gas for work van",
            category: "transportation",
            amount: 75,
            date: "2025-09-18",
            notes: "Weekly fuel",
          },
          {
            id: "E4",
            professionalId: userName,
            name: "Materials for Water Heater Maintenance",
            category: "materials",
            amount: 75,
            date: "2025-09-25",
            relatedJobId: "J3",
            relatedJobName: "Water Heater Maintenance",
            notes: "Auto-generated from job: Water Heater Maintenance",
            autoGenerated: true,
          },
          {
            id: "E5",
            professionalId: userName,
            name: "Tool maintenance",
            category: "miscellaneous",
            amount: 45,
            date: "2025-09-28",
            notes: "Sharpening and repairs",
          },
        ]
        sessionStorage.setItem("professionalExpenses", JSON.stringify(INITIAL_EXPENSES))
      }
      
      router.push("/professional/home")
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-background via-background to-secondary/20 p-4">
      <div className="w-full max-w-md space-y-6 animate-fadeIn">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors hover-lift"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to home
        </Link>

        <Card className="border-2 card-hover shadow-lg">
          <CardHeader className="space-y-3">
            <div className="flex items-center gap-3">
              <div className="gradient-accent rounded-xl p-3 shadow-glow-accent">
                <Wrench className="w-7 h-7 text-accent-foreground" />
              </div>
              <CardTitle className="text-3xl font-bold">Professional Sign-In</CardTitle>
            </div>
            <CardDescription className="text-base">
              {isNewUser ? "Create your professional profile and start connecting with clients" : "Sign in to manage your business"}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-3">
                <Label htmlFor="userName" className="text-base font-medium">Username</Label>
                <Input
                  id="userName"
                  type="text"
                  placeholder="Enter your username"
                  value={userName}
                  onChange={(e) => setUserName(e.target.value)}
                  required
                  className="h-12 border-2 focus:border-accent transition-all"
                />
              </div>

              {isNewUser && (
                <div className="space-y-4 animate-fadeIn">
                  <div className="space-y-3">
                    <Label htmlFor="businessName" className="text-base font-medium">Business Name</Label>
                    <Input
                      id="businessName"
                      type="text"
                      placeholder="Enter your business name"
                      value={businessName}
                      onChange={(e) => setBusinessName(e.target.value)}
                      required
                      className="h-12 border-2 focus:border-accent transition-all"
                    />
                  </div>

                  <div className="space-y-3">
                    <Label htmlFor="category" className="text-base font-medium">Service Category</Label>
                    <Select value={category} onValueChange={setCategory} required>
                      <SelectTrigger id="category" className="h-12 border-2">
                        <SelectValue placeholder="Select a category" />
                      </SelectTrigger>
                      <SelectContent>
                        {CATEGORIES.map((cat) => (
                          <SelectItem key={cat} value={cat}>
                            {cat}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              )}

              <Button 
                type="submit" 
                className="w-full h-12 gradient-accent text-accent-foreground btn-scale shadow-lg text-lg font-semibold" 
                size="lg"
              >
                {isNewUser ? "Create Account" : "Sign In"}
              </Button>

              <Button 
                type="button" 
                variant="ghost" 
                className="w-full hover-lift" 
                onClick={() => setIsNewUser(!isNewUser)}
              >
                {isNewUser ? "Already have an account? Sign in" : "New professional? Sign up"}
              </Button>

              <p className="text-center text-sm text-muted-foreground">
                Looking for services?{" "}
                <Link href="/customer/login" className="text-accent font-medium hover:underline">
                  Sign in as Customer
                </Link>
              </p>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
