"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { Plus, Trash2, ArrowLeft, Filter, DollarSign, Calendar as CalendarIcon, Briefcase } from "lucide-react"
import { AppHeader } from "@/components/app-header"
import { toast } from "sonner"
import type { Job } from "@/app/professional/jobs/page"

export type Expense = {
  id: string
  professionalId: string
  name: string
  category: "materials" | "transportation" | "miscellaneous"
  amount: number
  date: string
  relatedJobId?: string
  relatedJobName?: string
  notes?: string
  autoGenerated?: boolean
}

// Initial mock expenses
const INITIAL_EXPENSES: Expense[] = [
  {
    id: "E1",
    professionalId: "",
    name: "Materials for Kitchen Sink Repair",
    category: "materials",
    amount: 50,
    date: "2025-09-15",
    relatedJobId: "J1",
    relatedJobName: "Kitchen Sink Repair",
    notes: "Auto-generated from job: Kitchen Sink Repair",
    autoGenerated: true,
  },
  {
    id: "E2",
    professionalId: "",
    name: "Materials for Bathroom Plumbing Installation",
    category: "materials",
    amount: 200,
    date: "2025-09-20",
    relatedJobId: "J2",
    relatedJobName: "Bathroom Plumbing Installation",
    notes: "Auto-generated from job: Bathroom Plumbing Installation",
    autoGenerated: true,
  },
  {
    id: "E3",
    professionalId: "",
    name: "Gas for work van",
    category: "transportation",
    amount: 75,
    date: "2025-09-18",
    notes: "Weekly fuel",
  },
  {
    id: "E4",
    professionalId: "",
    name: "Materials for Water Heater Maintenance",
    category: "materials",
    amount: 75,
    date: "2025-09-25",
    relatedJobId: "J3",
    relatedJobName: "Water Heater Maintenance",
    notes: "Auto-generated from job: Water Heater Maintenance",
    autoGenerated: true,
  },
  {
    id: "E5",
    professionalId: "",
    name: "Tool maintenance",
    category: "miscellaneous",
    amount: 45,
    date: "2025-09-28",
    notes: "Sharpening and repairs",
  },
]

export default function ProfessionalExpensesPage() {
  const router = useRouter()
  const [professionalName, setProfessionalName] = useState("")
  const [expenses, setExpenses] = useState<Expense[]>([])
  const [jobs, setJobs] = useState<Job[]>([])
  const [filter, setFilter] = useState<"all" | "materials" | "transportation" | "miscellaneous">("all")
  const [showAddForm, setShowAddForm] = useState(false)

  // Form state
  const [formData, setFormData] = useState({
    name: "",
    category: "materials" as "materials" | "transportation" | "miscellaneous",
    amount: "",
    date: new Date().toISOString().split("T")[0],
    relatedJobId: "",
    notes: "",
  })

  useEffect(() => {
    const name = sessionStorage.getItem("professionalName")
    if (!name) {
      router.push("/professional/login")
    } else {
      setProfessionalName(name)

      // Load expenses and jobs
      const savedExpenses = sessionStorage.getItem("professionalExpenses")
      if (savedExpenses) {
        setExpenses(JSON.parse(savedExpenses))
      } else {
        // Initialize with mock data
        setExpenses(INITIAL_EXPENSES)
        sessionStorage.setItem("professionalExpenses", JSON.stringify(INITIAL_EXPENSES))
      }

      const savedJobs = JSON.parse(sessionStorage.getItem("professionalJobs") || "[]")
      setJobs(savedJobs)
    }
  }, [router])

  if (!professionalName) return null

  const handleAddExpense = (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.name || !formData.amount || !formData.date) {
      toast.error("Please fill in all required fields")
      return
    }

    const selectedJob = jobs.find((j) => j.id === formData.relatedJobId)

    const newExpense: Expense = {
      id: `E${Date.now()}`,
      professionalId: professionalName,
      name: formData.name,
      category: formData.category,
      amount: parseFloat(formData.amount),
      date: formData.date,
      relatedJobId: formData.relatedJobId || undefined,
      relatedJobName: selectedJob?.jobName,
      notes: formData.notes || undefined,
      autoGenerated: false,
    }

    const updatedExpenses = [newExpense, ...expenses]
    setExpenses(updatedExpenses)
    sessionStorage.setItem("professionalExpenses", JSON.stringify(updatedExpenses))

    toast.success("Expense added successfully!")

    // Reset form
    setFormData({
      name: "",
      category: "materials",
      amount: "",
      date: new Date().toISOString().split("T")[0],
      relatedJobId: "",
      notes: "",
    })
    setShowAddForm(false)
  }

  const handleDeleteExpense = (id: string) => {
    const expense = expenses.find((e) => e.id === id)
    if (expense?.autoGenerated) {
      toast.error("Cannot delete auto-generated expenses from jobs")
      return
    }

    const updatedExpenses = expenses.filter((e) => e.id !== id)
    setExpenses(updatedExpenses)
    sessionStorage.setItem("professionalExpenses", JSON.stringify(updatedExpenses))
    toast.success("Expense deleted")
  }

  const filteredExpenses = expenses.filter((exp) => {
    if (filter === "all") return true
    return exp.category === filter
  })

  // Calculate totals
  const totalExpenses = expenses.reduce((sum, exp) => sum + exp.amount, 0)
  const materialsCost = expenses.filter((e) => e.category === "materials").reduce((sum, exp) => sum + exp.amount, 0)
  const transportationCost = expenses
    .filter((e) => e.category === "transportation")
    .reduce((sum, exp) => sum + exp.amount, 0)
  const miscellaneousCost = expenses
    .filter((e) => e.category === "miscellaneous")
    .reduce((sum, exp) => sum + exp.amount, 0)

  // Calculate monthly expenses
  const monthlyExpenses = expenses.reduce(
    (acc, exp) => {
      const month = new Date(exp.date).toLocaleString("en-US", { month: "short", year: "numeric" })
      if (!acc[month]) {
        acc[month] = 0
      }
      acc[month] += exp.amount
      return acc
    },
    {} as Record<string, number>,
  )

  const getCategoryColor = (category: string) => {
    switch (category) {
      case "materials":
        return "text-blue-600 border-blue-600 bg-blue-500/10"
      case "transportation":
        return "text-purple-600 border-purple-600 bg-purple-500/10"
      case "miscellaneous":
        return "text-orange-600 border-orange-600 bg-orange-500/10"
      default:
        return "text-gray-600 border-gray-600 bg-gray-500/10"
    }
  }

  return (
    <>
      <AppHeader />
      <div className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20">
        <div className="max-w-7xl mx-auto p-6 space-y-6">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" className="gap-2 -ml-2" onClick={() => router.push("/professional/home")}>
                <ArrowLeft className="w-4 h-4" />
                Back
              </Button>
              <div>
                <h1 className="text-3xl font-bold text-foreground">Expense Tracking</h1>
                <p className="text-muted-foreground mt-1">Track and categorize your business expenses</p>
              </div>
            </div>
            <Button onClick={() => setShowAddForm(!showAddForm)} className="gap-2">
              <Plus className="w-4 h-4" />
              Add Expense
            </Button>
          </div>

          {/* Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card className="border-2">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Total Expenses</p>
                    <p className="text-2xl font-bold text-foreground mt-1">${totalExpenses.toFixed(2)}</p>
                  </div>
                  <div className="bg-red-500/10 p-3 rounded-full">
                    <DollarSign className="w-6 h-6 text-red-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-2">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Materials</p>
                    <p className="text-2xl font-bold text-blue-600 mt-1">${materialsCost.toFixed(2)}</p>
                  </div>
                  <div className="bg-blue-500/10 p-3 rounded-full">
                    <Briefcase className="w-6 h-6 text-blue-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-2">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Transportation</p>
                    <p className="text-2xl font-bold text-purple-600 mt-1">${transportationCost.toFixed(2)}</p>
                  </div>
                  <div className="bg-purple-500/10 p-3 rounded-full">
                    <CalendarIcon className="w-6 h-6 text-purple-600" />
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-2">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Miscellaneous</p>
                    <p className="text-2xl font-bold text-orange-600 mt-1">${miscellaneousCost.toFixed(2)}</p>
                  </div>
                  <div className="bg-orange-500/10 p-3 rounded-full">
                    <DollarSign className="w-6 h-6 text-orange-600" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Add Expense Form */}
          {showAddForm && (
            <Card className="border-2 border-primary">
              <CardHeader>
                <CardTitle>Add New Expense</CardTitle>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleAddExpense} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="name">Expense Name *</Label>
                      <Input
                        id="name"
                        value={formData.name}
                        onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                        placeholder="e.g., Gas for van"
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="category">Category *</Label>
                      <Select
                        value={formData.category}
                        onValueChange={(value: "materials" | "transportation" | "miscellaneous") =>
                          setFormData({ ...formData, category: value })
                        }
                      >
                        <SelectTrigger id="category">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="materials">Materials</SelectItem>
                          <SelectItem value="transportation">Transportation</SelectItem>
                          <SelectItem value="miscellaneous">Miscellaneous</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="amount">Amount *</Label>
                      <Input
                        id="amount"
                        type="number"
                        step="0.01"
                        min="0"
                        value={formData.amount}
                        onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                        placeholder="0.00"
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="date">Date *</Label>
                      <Input
                        id="date"
                        type="date"
                        value={formData.date}
                        onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="relatedJob">Related Job (Optional)</Label>
                      <Select
                        value={formData.relatedJobId}
                        onValueChange={(value) => setFormData({ ...formData, relatedJobId: value })}
                      >
                        <SelectTrigger id="relatedJob">
                          <SelectValue placeholder="Select a job (optional)" />
                        </SelectTrigger>
                        <SelectContent>
                          {jobs.map((job) => (
                            <SelectItem key={job.id} value={job.id}>
                              {job.jobName} - {job.customerName}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2 md:col-span-2">
                      <Label htmlFor="notes">Notes (Optional)</Label>
                      <Input
                        id="notes"
                        value={formData.notes}
                        onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                        placeholder="Additional details"
                      />
                    </div>
                  </div>

                  <div className="flex gap-2 justify-end">
                    <Button type="button" variant="outline" onClick={() => setShowAddForm(false)}>
                      Cancel
                    </Button>
                    <Button type="submit">Add Expense</Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          )}

          {/* Filter Buttons */}
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-muted-foreground" />
            <Button variant={filter === "all" ? "default" : "outline"} size="sm" onClick={() => setFilter("all")}>
              All ({expenses.length})
            </Button>
            <Button
              variant={filter === "materials" ? "default" : "outline"}
              size="sm"
              onClick={() => setFilter("materials")}
            >
              Materials ({expenses.filter((e) => e.category === "materials").length})
            </Button>
            <Button
              variant={filter === "transportation" ? "default" : "outline"}
              size="sm"
              onClick={() => setFilter("transportation")}
            >
              Transportation ({expenses.filter((e) => e.category === "transportation").length})
            </Button>
            <Button
              variant={filter === "miscellaneous" ? "default" : "outline"}
              size="sm"
              onClick={() => setFilter("miscellaneous")}
            >
              Miscellaneous ({expenses.filter((e) => e.category === "miscellaneous").length})
            </Button>
          </div>

          {/* Expenses List */}
          <Card className="border-2">
            <CardHeader>
              <CardTitle>Expense History</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {filteredExpenses.length === 0 ? (
                  <p className="text-center text-muted-foreground py-8">No expenses found</p>
                ) : (
                  filteredExpenses.map((expense) => (
                    <Card key={expense.id} className="border">
                      <CardContent className="p-4">
                        <div className="flex items-start justify-between gap-4">
                          <div className="flex-1 space-y-2">
                            <div className="flex items-center gap-2 flex-wrap">
                              <h3 className="font-semibold text-foreground">{expense.name}</h3>
                              <Badge variant="outline" className={getCategoryColor(expense.category)}>
                                {expense.category.charAt(0).toUpperCase() + expense.category.slice(1)}
                              </Badge>
                              {expense.autoGenerated && (
                                <Badge variant="secondary" className="text-xs">
                                  Auto-generated
                                </Badge>
                              )}
                            </div>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-sm">
                              <div className="flex items-center gap-2 text-muted-foreground">
                                <CalendarIcon className="w-4 h-4" />
                                {new Date(expense.date).toLocaleDateString()}
                              </div>
                              <div className="flex items-center gap-2 text-muted-foreground">
                                <DollarSign className="w-4 h-4" />
                                ${expense.amount.toFixed(2)}
                              </div>
                              {expense.relatedJobName && (
                                <div className="flex items-center gap-2 text-muted-foreground">
                                  <Briefcase className="w-4 h-4" />
                                  {expense.relatedJobName}
                                </div>
                              )}
                            </div>
                            {expense.notes && <p className="text-sm text-muted-foreground italic">{expense.notes}</p>}
                          </div>
                          {!expense.autoGenerated && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleDeleteExpense(expense.id)}
                              className="text-destructive hover:text-destructive"
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  ))
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </>
  )
}

